# Generated by Django 6.0.3 on 2026-04-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Коли виконати (нагадування)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Деталі завдання'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Що зробити?'),
        ),
    ]
